export const letterExamples: { [key: string]: { emoji: string; word: string } } = {
  A: { emoji: '🍎', word: 'Apple' },
  B: { emoji: '🦋', word: 'Butterfly' },
  C: { emoji: '🐱', word: 'Cat' },
  D: { emoji: '🦕', word: 'Dinosaur' },
  E: { emoji: '🐘', word: 'Elephant' },
  F: { emoji: '🐸', word: 'Frog' },
  G: { emoji: '🦒', word: 'Giraffe' },
  H: { emoji: '🏠', word: 'House' },
  I: { emoji: '🍦', word: 'Ice Cream' },
  J: { emoji: '🤹', word: 'Juggle' },
  K: { emoji: '🪁', word: 'Kite' },
  L: { emoji: '🦁', word: 'Lion' },
  M: { emoji: '🌙', word: 'Moon' },
  N: { emoji: '🥜', word: 'Nut' },
  O: { emoji: '🐙', word: 'Octopus' },
  P: { emoji: '🐧', word: 'Penguin' },
  Q: { emoji: '👑', word: 'Queen' },
  R: { emoji: '🌈', word: 'Rainbow' },
  S: { emoji: '⭐', word: 'Star' },
  T: { emoji: '🐯', word: 'Tiger' },
  U: { emoji: '☔', word: 'Umbrella' },
  V: { emoji: '🎻', word: 'Violin' },
  W: { emoji: '🍉', word: 'Watermelon' },
  X: { emoji: '🎄', word: 'Xmas Tree' },
  Y: { emoji: '🧶', word: 'Yarn' },
  Z: { emoji: '🦓', word: 'Zebra' }
}
